// Complete list of crime types for Journal de Crime
export const CRIME_TYPES = [
  { value: 'outrage_a_agent', label: 'Outrage à agent' },
  { value: 'menace_verbale', label: 'Menace verbale ou intimidation' },
  { value: 'dissimulation_visage', label: 'Dissimulation du visage' },
  { value: 'agression', label: 'Agression' },
  { value: 'arme_letale_ville', label: 'Arme létale sortie en ville' },
  { value: 'braquage_atm', label: 'Braquage d\'ATM' },
  { value: 'braquage_civil', label: 'Braquage de civil' },
  { value: 'braquage_coiffeur', label: 'Braquage de coiffeur' },
  { value: 'braquage_ammunation', label: 'Braquage d\'Ammunation' },
  { value: 'braquage_magasin_vetements', label: 'Braquage de magasin de vêtements' },
  { value: 'braquage_tatoueur', label: 'Braquage de tatoueur' },
  { value: 'braquage_superette', label: 'Braquage de supérette' },
  { value: 'braquage_fleeca_bank', label: 'Braquage de banque (Fleeca Bank)' },
  { value: 'braquage_convoi', label: 'Braquage de convoi' },
  { value: 'braquage_fourgon_blind', label: 'Braquage de fourgon blindé' },
  { value: 'braquage_bijouterie', label: 'Braquage de bijouterie' },
  { value: 'braquage_entreprise', label: 'Braquage d\'entreprise' },
  { value: 'braquage_sandy_shore', label: 'Braquage Sandy Shore Bank' },
  { value: 'braquage_senora_central', label: 'Braquage Senora Central Bank' },
  { value: 'braquage_maze_bank', label: 'Braquage Maze Bank' },
  { value: 'braquage_casino', label: 'Braquage de casino' },
  { value: 'braquage_humans_labs', label: 'Braquage de Humans Labs' },
  { value: 'braquage_pacifique', label: 'Braquage de Pacifique' },
  { value: 'possession_objets_illegal', label: 'Possession d\'objets illégal' },
  { value: 'cambriolage', label: 'Cambriolage' },
  { value: 'delit_fuite', label: 'Délit de fuite' },
  { value: 'destruction_preuve', label: 'Destruction / dissimulation de preuve' },
  { value: 'fabrication_drogue', label: 'Fabrication de drogue' },
  { value: 'possession_drogue', label: 'Possession de drogue' },
  { value: 'vente_drogue_civils', label: 'Vente de drogue à des civils' },
  { value: 'port_arme_illegal', label: 'Port d\'arme illégal' },
  { value: 'port_arme_legal_sans_ppa', label: 'Port d\'armes légal sans PPA' },
  { value: 'argent_non_declare', label: 'Possession d\'argent non déclaré' },
  { value: 'gilet_par_balle', label: 'Détention de gilet par balle' },
  { value: 'refus_obtemperer', label: 'Refus d\'obtempérer' },
  { value: 'tir_ville', label: 'Tir en ville' },
  { value: 'tir_civil', label: 'Tir sur civil' },
  { value: 'usurpation_identite', label: 'Usurpation d\'identité' },
  { value: 'violation_propriete_gouv', label: 'Violation de propriété gouvernementale' },
  { value: 'vol_voiture', label: 'Vol de voiture' },
  { value: 'go_fast', label: 'Go fast' },
  { value: 'port_gilet_par_balle', label: 'Port du gilet par balles' },
  { value: 'entrave_operation_police', label: 'Entrave à une opération de police' },
  { value: 'combat_clandestin', label: 'Combat clandestin' },
  { value: 'vol_vehicule_entreprise', label: 'Vol de véhicules d\'entreprise' },
  { value: 'appartenance_gang', label: 'Appartenance à un gang' },
  { value: 'kidnapping', label: 'Kidnapping' },
  { value: 'blanchiment_argent', label: 'Blanchiment d\'argent' },
  { value: 'corruption', label: 'Corruption' },
  { value: 'menace_representant_etat', label: 'Menace agrave sur représentant de l\'État' },
  { value: 'tentative_meurtre', label: 'Tentative de meurtre' },
  { value: 'tentative_meurtre_agent', label: 'Tentative de meurtre sur agent de l\'État' },
  { value: 'tentative_prise_otage', label: 'Tentative de prise d\'otage' },
  { value: 'tentative_otage_agent', label: 'Tentative de prise d\'otage sur un agent de l\'État' },
  { value: 'usurpation_identite_gouv', label: 'Usurpation d\'identité gouvernementale' },
  { value: 'prise_otage_civil', label: 'Prise d\'otage sur civil' },
  { value: 'appartenance_org_criminelle', label: 'Appartenance à une organisation criminelle' },
  { value: 'attaque_convoi_federal', label: 'Attaque de convoi fédéral' },
  { value: 'prise_otage_agent', label: 'Prise d\'otage sur agent de l\'État' },
  { value: 'divulgation_infos_conf', label: 'Divulgation d\'informations confidentielles' },
  { value: 'desengagement_policier', label: 'Désengagement policier' },
  { value: 'haute_trahison', label: 'Haute trahison' },
  { value: 'attaque_bollingbroke', label: 'Attaque Bollingbroke Prison' },
  { value: 'traffic_kit_armes', label: 'Traffic de kit d\'armes' },
  { value: 'traffic_armes', label: 'Traffic d\'armes' },
  { value: 'traffic_gilet', label: 'Traffic de gilet par balle' },
  { value: 'traffic_drogue', label: 'Traffic de drogue' },
  { value: 'acte_terroriste', label: 'Acte terroriste' },
  { value: 'sequestration_agent', label: 'Séquestration sur agent de l\'État' },
];

export function getCrimeLabel(value: string): string {
  return CRIME_TYPES.find(c => c.value === value)?.label || value;
}
